language: python
dist: xenial

jobs:
  include:
    - stage: playbook run test
      name: python 2.7
      python: 2.7
      script: ansible-playbook tests/test_server_certificate_info.yml
    - name: python 3.5
      python: 3.5
      script: ansible-playbook tests/test_server_certificate_info.yml
    - name: python 3.6
      python: 3.5
      script: ansible-playbook tests/test_server_certificate_info.yml
    - name: python 3.7
      python: 3.7
      script: ansible-playbook tests/test_server_certificate_info.yml
    - name: python 3.8
      python: 3.8-dev
      script: ansible-playbook tests/test_server_certificate_info.yml
