---
- name: Generate of server certificate report
  hosts: localhost
  gather_facts: no
  vars:
    servers:
      - www.example.com
      - hogehoge22.com
  tasks:
    - name: Get certificate information from server.
      get_certificate:
        host: "{{ item }}"
        port: 443
      loop: "{{ servers }}"
      ignore_errors: yes
      register: certificate_result

    - name: Generate report.
      template:
        src: templates/server_certificate_report.j2
        dest: server_certificate_report.html
